name: Build Godot Project

on:
  workflow_dispatch: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [HTML5]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: index
          preset: ${{ matrix.platform }}
          debugMode: "false"
      - name: Download compo version
        uses: robinraju/release-downloader@v1.5
        with: 
          tag: "v0"
          fileName: "compo-initial-build.zip"
          out-file-path: "releases"
      - name: repack bundle
        run: |
          sudo su
          mkdir -p ${{ github.workspace }}/final-bundle/jam
          mkdir -p ${{ github.workspace }}/final-bundle/postjam
          ls -la ${{ github.workspace }}/${{ steps.build.outputs.build }}
          cd ${{ github.workspace }}/${{ steps.build.outputs.build }}
          find -type f . | xargs -L1 basename | xargs -L1 -I {} cp {} ${{ github.workspace }}/final-bundle/postjam
          unzip ${{ github.workspace }}/releases/compo-initial-build.zip -d ${{ github.workspace }}/final-bundle/jam
          cp ${{ github.workspace }}/launcher.html ${{ github.workspace }}/final-bundle/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/final-bundle/
